app/Http/routes.php
<?php


Route::get('/', function () {
    return view('site.index');
});
Route::get('/about', function () {
    return view('site.about');
});
Route::get('/contact', function () {
    return view('site.contact');
});
Route::get('/register', function () {
    return view('site.register');
});
Route::get('/login', function () {
    // dd(bcrypt(1));
    return view('site.login');
});
Route::get('/confirm', 'AuthCustomController@confirmMessage');
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('/register', 'AuthCustomController@create');
//Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/contact', function () {
    return view('site.contact');
});
Route::get('/confirm-email/{code}','AuthCustomController@confirmEmail');
Route::post('/authenticate','AuthCustomController@authenticate');

//user routes
Route::group(['middleware'=>'App\Http\Middleware\OnlyUser','prefix'=>'/user'],function()
{
    Route::get('/welcome','UserController@index');
    Route::get('/dashboard',[
        'as' => 'user.dashboard',
        'uses' => 'UserController@index'
        ]);
	Route::get('/profile',[
        'as'=>'user.profile','uses'=>'UserController@viewProfile'
        ]);
    Route::get('/profile/edit',[
        'as'=>'user.edit','uses'=>'UserController@edit'
        ]);
    Route::post('/profile/update',[
        'as'=>'user.update','uses'=>'UserController@update'
        ]);
    //news 
    //activity
    //gallery
    Route::resource('news','NewsController');
    Route::get('/user/news/{id}/delete',
        ['as'=>'user.news.delete','NewsController@destroy']);
    Route::resource('articles','ArticlesController');
    Route::get('/user/articles/{id}/delete',
        ['as'=>'user.articles.delete','ArticlesController@destroy']);
    Route::resource('galleries','GalleriesController');
    Route::post('/user/galleries/create',
        ['as'=>'user.galleries.addImages','uses'=>'GalleriesController@create']);
    Route::resource('categories','CategoriesController');
    Route::get('/user/categories/{id}/delete',
        ['as'=>'user.categories.delete','uses'=>'CategoriesController@destroy']);
    Route::get('/user/category/{id}/galleries',
        ['as'=>'gallery.category','uses'=>'GalleriesController@showGalleryCategoryWise']);
    Route::post('/user/galleries/destroy',
        ['as'=>'galleries.destroy','uses'=>'GalleriesController@Destroy']);
});
Route::group(['middleware'=>'App\Http\Middleware\OnlyAdmin','prefix'=>'/admin'],function()
{
	Route::get('/welcome','AdminController@index');
	Route::get('/users',['as'=>'users.index','uses'=>'AdminController@users']);
	Route::get('/user/approve/{id}','AdminController@approve');
    Route::get('/news',
        ['as'=>'admin.news','uses'=>'NewsController@adminNews']);
    Route::get('/news/approve-disapprove/{id}',
        ['as'=>'admin.news.approve','uses'=>'NewsController@adminApprove']);
    Route::get('/news/{id}',
        ['as'=>'admin.news.show','uses'=>'NewsController@adminShow']);

    Route::get('/articles',
        ['as'=>'admin.articles','uses'=>'ArticlesController@adminNews']);
    Route::get('/articles/approve-disapprove/{id}',
        ['as'=>'admin.articles.approve','uses'=>'ArticlesController@adminApprove']);
    Route::get('/articles/{id}',
        ['as'=>'admin.articles.show','uses'=>'ArticlesController@adminShow']);
    Route::get('/galleries',
        ['as'=>'admin.galleries.index','uses'=>'GalleriesController@adminIndex']);
    Route::get('/categories/{id}/galleries',
        ['as'=>'admin.categories.galleries','uses'=>'GalleriesController@adminGalleryCategoryWise']);
    Route::get('/galleries/approve-disapprove/{id}',
        ['as'=>'admin.galleries.approve','uses'=>'GalleriesController@adminApprove']);
    Route::get('/galleries/approve-bulk',
        ['as'=>'admin.galleries.approveBulk','uses'=>'GalleriesController@adminApproveBulk']);

});

Route::get('/members','MembersController@index');
Route::get('/members/{type}','MembersController@index');
Route::get('/members{members-details}','MembersController@details');

Route::get('/articles',[
    'as'=>'site.articles.index','uses'=>'SiteArticleController@index']);
Route::get('/article/{id}',
    ['as'=>'site.article.show','uses'=>'SiteArticleController@show']);

Route::get('/gallery','SiteGalleryController@index');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','confirm','code','user_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function details()
    {
        return $this->hasOne('App\UserDetail');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
class UserController extends BaseController
{
    function index()
    {
    	return view('user.index');
    }

    function viewProfile()
    {
    	return view('user.profile');
    }

    function edit()
    {
    	return view('user.edit');
    }

    function update(Request $req)
    {
    	$user=User::findOrFail($this->user->id);
    	$fName=$req->input('f_name');
    	$lName=$req->input('l_name');
    	$password=$req->input('password');
    	$type=$req->input('user_type');
    	$about=$req->input('about_you');
    	$file=$req->file('avatar');
    	if($file){
    		$url=md5(time()).$file->getClientOriginalName();
    		$file->move('docs/',$url);
    		$url='docs/'.$url;
    		$user->details->avatar=$url;
    	}
    	if($password)
    		$user->password=bcrypt($password);
    	$user->details->f_name=$fName;
    	$user->details->l_name=$lName;
    	$user->details->user_type_id=$type;
    	$user->user_type=$type;
    	$user->details->about_you=$about;
    	$user->save();
    	$user->details->save();
    	return redirect()->back();

    }
}

resources/views/user/control-sidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-user bg-yellow"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

              <p>New phone +1(800)555-1234</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

              <p>nora@example.com</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-file-code-o bg-green"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

              <p>Execution time 5 seconds</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Update Resume
              <span class="label label-success pull-right">95%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-success" style="width: 95%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Laravel Integration
              <span class="label label-warning pull-right">50%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Back End Framework
              <span class="label label-primary pull-right">68%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Allow mail redirect
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Other sets of options are available
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Expose author name in posts
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Allow the user to show his name in blog posts
          </p>
        </div>
        <!-- /.form-group -->

        <h3 class="control-sidebar-heading">Chat Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Show me as online
            <input type="checkbox" class="pull-right" checked>
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Turn off notifications
            <input type="checkbox" class="pull-right">
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Delete chat history
            <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
          </label>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<!-- /.control-sidebar -->

resources/views/user/edit.blade.php
@extends("user.master")
@section("content")
<section class="content">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Profile</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            {!! Form::open(['route'=>'user.update','files'=>true]) !!}
              <div class="box-body">
                <div class="form-group">
                  <label for="f_name">First Name</label>
                  <input type="text" required class="form-control" id="f_name" name="f_name" placeholder="Enter First Name"
                  value="{{$details->f_name}}">
                </div>
                <div class="form-group">
                  <label for="l_name">Last Name</label>
                  <input type="text" name="l_name" class="form-control" id="l_name" placeholder="Enter Last Name"
                  value="{{$details->l_name}}">
                </div>
                <div class="form-group">
                  <label for="password">Change Password</label>
                  <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                </div>
                <div class="form-group">
                  <label for="avatar">Avatar</label>
                  <input type="file" accept="image/x-png, image/gif, image/jpeg" id="avatar" name="avatar">
                </div>
                <div class="form-group">
                <label>User Type</label>  
                <div class="radio">
                  
                  <label>
                    <input type="radio" name="user_type" {{$details->user_type_id==1?'checked':''}} value="1"> Army
                  </label>
                  <label>
                    <input type="radio" name="user_type" {{$details->user_type_id==2?'checked':''}} value="2"> Navy
                  </label>
                  <label>
                    <input type="radio" name="user_type" {{$details->user_type_id==3?'checked':''}} value="3"> Air Force
                  </label>
                </div>
                </div>
                
                <div class="form-group">
                  <label for="about_you">About You</label>
                  <textarea class="editor form-control" id="about_you" placeholder="about you" name="about_you" rows="5">{{$details->about_you}}</textarea>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-block btn-warning">
                <i class="fa fa-save"></i> Upate</button>
              </div>
            {!! Form::close() !!}
          </div>
    </div>
  </div>
</section>
     
@stop

resources/views/user/footer.blade.php
</body>
</html>

resources/views/user/header.blade.php
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>user</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{{asset("vendor/bootstrap/dist/css/bootstrap.min.css")}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset("css/AdminLTE.min.css")}}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
 folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset("css/skins/_all-skins.min.css")}}">
<!-- iCheck -->
<link rel="stylesheet" href="{{asset("plugins/iCheck/flat/blue.css")}}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{asset("plugins/morris/morris.css")}}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{asset("plugins/jvectormap/jquery-jvectormap-1.2.2.css")}}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{asset("plugins/datepicker/datepicker3.css")}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset("plugins/daterangepicker/daterangepicker-bs3.css")}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset("plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css")}}">

<link rel="stylesheet" href="{{asset("css/main.css")}}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

<header class="main-header">
<!-- Logo -->
<a href="index2.html" class="logo">
<!-- mini logo for sidebar mini 50x50 pixels -->
<!-- <span class="logo-mini"><b>A</b>LT</span> -->
<!-- logo for regular state and mobile devices -->
<span class="logo-lg"><b></b></span>
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
<!-- Sidebar toggle button-->
<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
  <span class="sr-only">Toggle navigation</span>
</a>

<div class="navbar-custom-menu">
  <ul class="nav navbar-nav">
    
    <li class="dropdown user user-menu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{asset($user->details->avatar?:'img/user.png')}}" class="user-image" alt="User Image">
        <span class="hidden-xs">{{$user->email}}</span>
      </a>
      <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
          <img src="{{asset($user->details->avatar?:'img/user.png')}}" class="img-circle" alt="User Image">

          <p>
            {{$user->name}}
            <small>Member since {{$user->created_at}}</small>
          </p>
        </li>
        <!-- Menu Body -->
        
        <!-- Menu Footer-->
        <li class="user-footer">
          <div class="pull-left">
            <a href="{{route('user.profile')}}" class="btn btn-default btn-flat">Profile</a>
          </div>
          <div class="pull-right">
            <a href="{{url('auth/logout')}}" class="btn btn-default btn-flat">Sign out</a>
          </div>
        </li>
      </ul>
    </li>
    <!-- Control Sidebar Toggle Button -->
   <!--  <li>
     <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
   </li> -->
  </ul>
</div>
</nav>
</header>

resources/views/user/index.blade.php
@extends("user.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Hi</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <!-- <i class="fa fa-minus"></i></button> -->
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        <div class="box-body">
          <!-- Start creating your amazing application! -->
          Welcome  {{$user->email}}
        </div>
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@stop

resources/views/user/master.blade.php
@include('user.header')
  <!-- Left side column. contains the logo and sidebar -->
  @include('user.sidebar')
  @include('scripts')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield("content")    
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      
    </div>
    <strong>
  </footer>

 {{-- @include('admin.control-sidebar') --}}
  
</div>
<!-- ./wrapper -->
@include('user.footer')

resources/views/user/profile.blade.php
@extends("user.master")
@section("content")
<section class="content">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="{{asset($user->details->avatar?:'img/user.png')}}" alt="User profile picture">

              <h3 class="profile-username text-center text-capitalize">
                {{full_name($user->details)}}
              </h3>

              <p class="text-muted text-center text-capitalize">
                {{userType($user->user_type)}}
              </p>

              <ul class="text-capitalize list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Name</b> <a class="pull-right">{{full_name($user->details)}}</a>
                </li>
                <li class="list-group-item">
                  <b>Gender</b> <a class="pull-right">{{gender($user->details->gender)}}</a>
                </li>
                <li class="list-group-item">
                  <b>User Type</b> <a class="pull-right">
                    {{userType($user->details->user_type_id)}}
                  </a>
                </li>
              </ul>

              <a href="{{route('user.edit')}}" class="btn btn-primary btn-block">
              <i class="fa fa-pencil"></i> <b>Edit</b>
              </a>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          <!-- About Me Box -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">About Me</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <!-- <strong><i class="fa fa-book margin-r-5"></i> Education</strong> -->

              <p class="text-muted">
                {{$user->details->about_you}}
              </p>

              <hr>

              
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
  </div>
</section>
      
@stop

resources/views/user/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{asset($user->details->avatar?:'img/user.png')}}" class="img-circle" alt="User Image" style="height: 60px">
        </div>
        <div class="pull-left info text-capitalize">
          <p class="text-capitalize">{{full_name($user->details)}}</p>
          <a href="#">
            {{userType($details->user_type_id)}}
          </a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="{{route('user.dashboard')}}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
          </a>
        </li>
        <li class="active treeview">
          <a href="{{route('user.profile')}}">
            <i class="fa fa-user"></i> <span>Profile</span> 
          </a>
        </li>
        <li class="active treeview">
          <a href="{{route('user.news.index')}}">
            <i class="fa fa-newspaper-o"></i> <span>News</span> 
          </a>
          <a href="{{route('user.articles.index')}}">
            <i class="fa fa-file-pdf-o"></i> <span>Articles</span> 
          </a>
          <a href="{{route('user.galleries.index')}}">
            <i class="fa  fa-file-image-o"></i> <span>Gallery</span>
          </a>
          <a href="{{route('user.categories.index')}}">
            <i class="fa  fa-file-text-o"></i> <span>Category</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

resources/views/user/user.blade.php
@extends("admin.master")
@section("content")
<section class="content">
	<div class="box">
            <div class="box-header">
              <h3 class="box-title">User</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-striped">
                <tbody><tr>
                  <th style="width: 10px">#</th>
                  <th>name</th>
                  <th>Email</th>
                  <th>gender</th>
                  <th>type</th>
                  <th>verified</th>
                  <th>Approved</th>
                  <th>Action</th>
                </tr>
                <?php $x=0 ?>
                @foreach($users as  $us)
                	<tr>
                		<td>{{++$x}}</td>
                    <td>{{full_name($us->details)}}</td>
                		<td>{{$us->email}}</td>
                		<td>{{gender($us->details->gender)}}</td>
                		<td>{{userType($us->details->user_type_id)}}</td>
                		<td>
                			@if($us->confirm)
                			<span class="badge bg-green">yes</span>
                			@else
                			<span class="badge bg-red">no</span>
                			@endif
                		</td>
                		<td>
                			@if($us->allowed)
                			<span class="badge bg-green">yes</span>
                			@else
                      <a href="{{url('admin/user/approve/'.$us->id)}}">
                			<span class="badge bg-red">no</span>
                      </a>
                			@endif
                		</td>
                    <td></td>
                	</tr>
                @endforeach
                
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>   
</section>
{{$users->links()}}
@stop