app/Http/routes.php
<?php


Route::get('/', function () {
    return view('site.index');
});
Route::get('/about', function () {
    return view('site.about');
});
Route::get('/contact', function () {
    return view('site.contact');
});
Route::get('/register', function () {
    return view('site.register');
});
Route::get('/login', function () {
    // dd(bcrypt(1));
    return view('site.login');
});
Route::get('/confirm', 'AuthCustomController@confirmMessage');
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('/register', 'AuthCustomController@create');
//Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/contact', function () {
    return view('site.contact');
});
Route::get('/confirm-email/{code}','AuthCustomController@confirmEmail');
Route::post('/authenticate','AuthCustomController@authenticate');

//user routes
Route::group(['middleware'=>'App\Http\Middleware\OnlyUser','prefix'=>'/user'],function()
{
    Route::get('/welcome','UserController@index');
    Route::get('/dashboard',[
        'as' => 'user.dashboard',
        'uses' => 'UserController@index'
        ]);
	Route::get('/profile',[
        'as'=>'user.profile','uses'=>'UserController@viewProfile'
        ]);
    Route::get('/profile/edit',[
        'as'=>'user.edit','uses'=>'UserController@edit'
        ]);
    Route::post('/profile/update',[
        'as'=>'user.update','uses'=>'UserController@update'
        ]);
    //news 
    //activity
    //gallery
    Route::resource('news','NewsController');
    Route::get('/user/news/{id}/delete',
        ['as'=>'user.news.delete','NewsController@destroy']);
    Route::resource('articles','ArticlesController');
    Route::get('/user/articles/{id}/delete',
        ['as'=>'user.articles.delete','ArticlesController@destroy']);
    Route::resource('galleries','GalleriesController');
    Route::post('/user/galleries/create',
        ['as'=>'user.galleries.addImages','uses'=>'GalleriesController@create']);
    Route::resource('categories','CategoriesController');
    Route::get('/user/categories/{id}/delete',
        ['as'=>'user.categories.delete','uses'=>'CategoriesController@destroy']);
    Route::get('/user/category/{id}/galleries',
        ['as'=>'gallery.category','uses'=>'GalleriesController@showGalleryCategoryWise']);
    Route::post('/user/galleries/destroy',
        ['as'=>'galleries.destroy','uses'=>'GalleriesController@Destroy']);
});
Route::group(['middleware'=>'App\Http\Middleware\OnlyAdmin','prefix'=>'/admin'],function()
{
	Route::get('/welcome','AdminController@index');
	Route::get('/users',['as'=>'users.index','uses'=>'AdminController@users']);
	Route::get('/user/approve/{id}','AdminController@approve');
    Route::get('/news',
        ['as'=>'admin.news','uses'=>'NewsController@adminNews']);
    Route::get('/news/approve-disapprove/{id}',
        ['as'=>'admin.news.approve','uses'=>'NewsController@adminApprove']);
    Route::get('/news/{id}',
        ['as'=>'admin.news.show','uses'=>'NewsController@adminShow']);

    Route::get('/articles',
        ['as'=>'admin.articles','uses'=>'ArticlesController@adminNews']);
    Route::get('/articles/approve-disapprove/{id}',
        ['as'=>'admin.articles.approve','uses'=>'ArticlesController@adminApprove']);
    Route::get('/articles/{id}',
        ['as'=>'admin.articles.show','uses'=>'ArticlesController@adminShow']);
    Route::get('/galleries',
        ['as'=>'admin.galleries.index','uses'=>'GalleriesController@adminIndex']);
    Route::get('/categories/{id}/galleries',
        ['as'=>'admin.categories.galleries','uses'=>'GalleriesController@adminGalleryCategoryWise']);
    Route::get('/galleries/approve-disapprove/{id}',
        ['as'=>'admin.galleries.approve','uses'=>'GalleriesController@adminApprove']);
    Route::get('/galleries/approve-bulk',
        ['as'=>'admin.galleries.approveBulk','uses'=>'GalleriesController@adminApproveBulk']);

});

Route::get('/members','MembersController@index');
Route::get('/members/{type}','MembersController@index');
Route::get('/members{members-details}','MembersController@details');

Route::get('/articles',[
    'as'=>'site.articles.index','uses'=>'SiteArticleController@index']);
Route::get('/article/{id}',
    ['as'=>'site.article.show','uses'=>'SiteArticleController@show']);

Route::get('/gallery','SiteGalleryController@index');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class News extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'topic', 'user_id', 'link','url','description','approved'
    ];

    protected $table='news';

    protected $dates=['approved']   ;

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use App\News;

class NewsController extends BaseController
{
    function index()
    {
    	$news=News::orderBy('updated_at','DESC')->whereUserId($this->user->id)
                    ->paginate(30);

        return view('news.index',compact('news'));
    }

    function show($id)
    {
        $new=News::findOrFail($id);
    	return view('news.view',compact('new'));
    }

    function create()
    {
        return view('news.create');
    }

    function store(Request $req)
    {
        $new=new News;
        $new->topic=$req->input('topic');
        $new->link=$req->input('link');
        $new->description=$req->input('description');
        $new->user_id=$this->user->id;
        $new->topic=$req->input('topic');
        $new->topic=$req->input('topic');
        $file=$req->file('file');
        if($file){
            $folder='docs/';
            $name=md5(time()).$file->getClientOriginalName();
            $file->move($folder,$name);
            $new->url=$folder.$name;
        }
        $new->save();
        return redirect()->route('user.news.index');
    }

    function edit($id)
    {
        $new=News::findOrFail($id);
    	return view('news.edit',compact('new'));
    }

    function update($id,Request $req)
    {
        $new=News::findOrFail($id);
        $new->topic=$req->input('topic');
        $new->link=$req->input('link');
        $new->description=$req->input('description');
        $new->user_id=$this->user->id;
        $new->topic=$req->input('topic');
        $new->topic=$req->input('topic');
        $file=$req->file('file');
        if($file){
            $folder='docs/';
            $name=md5(time()).$file->getClientOriginalName();
            $file->move($folder,$name);
            $new->url=$folder.$name;
        }
        $new->save();
        return redirect()->route('user.news.index');
    }

    public function destroy($id)
    {
        $new=News::findOrFail($id);
        if($id->user_id==$this->user->id){
            $new->delete();
        }
        return redirect()->route('user.news.index');
    }

    public function adminNews()
    {
        $news=News::orderBy('approved','ASC')
                    ->paginate(30);
        return view('news.adminList',
            compact('news'));
    }

    public function adminApprove($id)
    {
        $new=News::findOrFail($id);
        if(!$new->approved){
            $new->approved=new \Carbon\Carbon;
        }else{
            $new->approved=null;
        }
        $new->save();
        return redirect()->back();
    } 

    public function adminShow($id)
    {
        $new=News::findOrFail($id);
        return view('news.Adminview',compact('new'));
    }
}

resources/views/news/Adminview.blade.php
@extends("admin.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h1 class="box-title text-capitalize">
               {{$new->topic}}

          </h1>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        <div class="box-body">
            <p class="help-block">Last Updated - {{$new->updated_at->format('M d Y h:m')}}</p>
           <blockquote>
             {!! $new->description !!}
           </blockquote>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          @if($new->link)
            <a target="_blank" href="{{$new->link}}">
              {{$new->link}}
            </a>
          @endif
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
      <div class="box box-solid">
            <div class="box-header with-border">
              
              <div class="col-xs-6">
                
                  @if($new->approved)
                  <a href="{{route('admin.news.approve',$new->id)}}" class="confirm btn btn-block btn-danger">
                  <i class="fa fa-remove"></i> Disapprove
                  </a>
                  @else
                  <a href="{{route('admin.news.approve',$new->id)}}" class="confirm btn btn-block btn-success">
                  <i class="fa fa-check"></i> Approve
                  </a>
                  @endif
                </a>
              </div>
            </div>
            
          </div>
    </section>
    <script type="text/javascript">
     /* $(function(){
        $("#description").wysihtml5();
      });*/
    </script>
@stop

resources/views/news/adminList.blade.php
@extends("admin.master")
@section("content")
<section class="content">
	<div class="box">
            <div class="box-header">
              <h3 class="box-title">News</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-striped">
                <tbody><tr>
                  <th style="width: 10px">#</th>
                  <th>topic</th>
                  <th>user</th>
                  <th>description</th>
                  <th>last updated</th>
                  <th>Approved</th>
                  <th>Action</th>
                </tr>
                <?php $x=0 ?>
                @foreach($news as  $new)
                	<tr>
                		<td>{{++$x}}</td>
                    <td>{{$new->topic}}</td>
                		<td>{{full_name($new->user->details)}}</td>
                		<td>{!!substr_close_tags($new->description,6)!!}</td>
                		<td>{{$new->updated_at->diffForHumans()}}</td>
                		<td>
                			@if($new->approved)
                			<a href="{{route('admin.news.approve',$new->id)}}">
                        <span class="badge bg-green">yes</span>  
                      </a>
                			@else
                      <a href="{{route('admin.news.approve',$new->id)}}">
                			<span class="badge bg-red">no</span>
                      </a>
                			@endif
                		</td>
                		<td>
                    <a target="_blank" href="{{route('admin.news.show',$new->id)}}">
                      View
                    </a>  
                    </td>
                	</tr>
                @endforeach
                
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>   

</section>
{{$news->links()}}
@stop

resources/views/news/create.blade.php
@extends("user.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
              Create News
          </h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <!-- <i class="fa fa-minus"></i></button> -->
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        {{Form::open(['role'=>'form','files'=>true,'route'=>'user.news.store'])}}
              <div class="box-body">
                <div class="form-group">
                  <label for="topic">Topic</label>
                  <input type="text" required name="topic" class="form-control" id="topic" placeholder="Enter Topic">
                </div>
                <div class="form-group">
                  <label for="link">Link To Article</label>
                  <input type="url" class="form-control" name="link" id="link" placeholder="Link To Article">
                </div>
                <div class="form-group">
                  <label for="file">File</label>
                  <input type="file" name="file" id="file" accept="application/pdf">

                  <!-- <p class="help-block">pdf </p> -->
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <textarea required class="form-control" id="description" name="description" rows="7" placeholder="Enter ..."></textarea>
                </div>
                
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <script type="text/javascript">
      $(function(){
        $("#description").wysihtml5();
      });
    </script>
@stop

resources/views/news/edit.blade.php
@extends("user.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
              Create News
          </h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <!-- <i class="fa fa-minus"></i></button> -->
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        {!! Form::open(['role'=>'form','files'=>true,'route'=>['user.news.update',$new->id]]) !!}
          {{Form::hidden('_method','PUT')}}
              <div class="box-body">
                <div class="form-group">
                  <label for="topic">Topic</label>
                  <input type="text" required name="topic" class="form-control" value="{{$new->topic}}" id="topic" placeholder="Enter Topic">
                </div>
                <div class="form-group">
                  <label for="link">Link To Article</label>
                  <input type="url" class="form-control" name="link" id="link" placeholder="Link To Article" value="{{$new->link}}">
                </div>
                <div class="form-group">
                  <label for="file">File</label>
                  <input type="file" name="file" id="file" accept="application/pdf">
                @if($new->url)
                  <p class="help-block">
                    <a href="{{asset($new->url)}}">
                      {{explode('/', $new->url)[1]}}
                    </a>
                  </p>
                @endif
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <textarea class="form-control" id="description" name="description" rows="7" placeholder="Enter ...">{!! $new->description !!}</textarea>
                </div>
                
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <script type="text/javascript">
      $(function(){
        $("#description").wysihtml5();
      });
    </script>
@stop

resources/views/news/index.blade.php
@extends("user.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <div class="col-xs-6">
              News
            </div>
            
          </h3>
          <div class="row">
            <div class="col-xs-3">
              <a href="{{route('user.news.create')}}" class="btn btn-block btn-info">Create</a>
            </div>
            <div class="col-xs-9">
             <span class="pull-right">
                {{$news->links()}}
             </span>
            </div>
          </div>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <!-- <i class="fa fa-minus"></i></button> -->
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        <div class="box-body">
          <!-- Start creating your amazing application! -->
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Topic</th>
                <th>Description</th>
                <th>last updated</th>
                <th>Approved</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($news as $new)
                <tr>
                  <td>{{@++$x}}</td>
                  <td>{{$new->topic}}</td>
                  <td>{!! substr_close_tags($new->description,20) !!}</td>
                  <td>{{$new->updated_at->diffForHumans()}}</td>
                  <td>
                    @if(!$new->approved)
                      <span class="badge bg-red">No</span>
                    @else
                      <span class="badge bg-green">
                        {{$new->approved->diffForHumans()}}
                      </span>
                    @endif
                  </td>
                  <td>
                    <div class="btn-group">
                      <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                        Action <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li> 
                          <a href="{{route('user.news.show',$new->id)}}">
                          <i class="fa fa-user"></i> view
                          </a>
                        </li>
                        <li>
                          
                          <a href="{{route('user.news.edit',$new->id)}}">
                            <i class="fa fa-pencil"></i> edit
                          </a>
                        </li>
                        <li>
                          <a href="">
                            <i class="fa fa-trash"></i> delete
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@stop

resources/views/news/view.blade.php
@extends("user.master")
@section("content")
<section class="content">
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h1 class="box-title text-capitalize">
               {{$new->topic}}

          </h1>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <!-- <i class="fa fa-minus"></i></button> -->
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <!-- <i class="fa fa-times"></i></button> -->
          </div>
        </div>
        <div class="box-body">
            <p class="help-block">Last Updated - {{$new->updated_at->format('M d Y h:m')}}</p>
           <blockquote>
             {!! $new->description !!}
           </blockquote>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          @if($new->link)
            <a target="_blank" href="{{$new->link}}">
              {{$new->link}}
            </a>
          @endif
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
      <div class="box box-solid">
            <div class="box-header with-border">
              <div class="col-xs-6">
                <a href="{{route('user.news.edit',$new->id)}}" class="confirm btn btn-block btn-warning">
                <i class="fa fa-pencil"></i> Edit
                </a>
              </div>
              <div class="col-xs-6">
                <a href="{{route('user.news.delete',$new->id)}}" class="confirm btn btn-block btn-danger">
                  <i class="fa fa-trash"></i> Delete
                </a>
              </div>
            </div>
            
          </div>
    </section>
    <script type="text/javascript">
     /* $(function(){
        $("#description").wysihtml5();
      });*/
    </script>
@stop